#!/usr/bin/env python
import os, sys

if len(sys.argv) != 3:
    print "Usage: convert-gtkbuild IN.GLADE OUT.C"
    exit(1)
    
IN, OUT = sys.argv[1:]

of = open( OUT, "w" )
f = open( IN, "r" )
d = f.read()
f.close()

of.write( """#include "sr-ts-glade.h"

const char* sr_ts_glade =
""" )

for l in d.splitlines():
    of.write('\t"')

    for c in l:
        if c == '"':
            c = "\\\""
        elif c == '\\':
            c = '\\\\'

        of.write( c )

    of.write('\\n"\n')
of.write(";\n")

of.close()
